version: "3.3"

services:
  #Système permettant la centralisation des cervices 
  traefik:
      image: "traefik:v2.10"
      container_name: "traefik"
      command:
        #- "--log.level=DEBUG"
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
      ports:
        - "90:80"
        - "8080:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
      networks:
        - loki
        