version: '3'

services:
  # Service MySQL pour WordPress
  db:
    image: mysql:5.7
    platform: linux/amd64  # Spécifiez l'architecture x86_64 si vous utilisez un système x86_64
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_wordpress_database
      MYSQL_USER: your_wordpress_user
      MYSQL_PASSWORD: your_wordpress_password
    networks:
      - db
      - external

  # Service WordPress
  wordpress:
    image: wordpress:latest
    platform: linux/arm64  # Spécifiez l'architecture ARM64
    depends_on:
      - db
    ports:
      - "8081:80"
    networks:
      - db
      - external
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: your_wordpress_user
      WORDPRESS_DB_PASSWORD: your_wordpress_password
      WORDPRESS_DB_NAME: your_wordpress_database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{wordpress}-web.rule=Host(`wordpress.td.anthonymoll.fr`)"
      - "traefik.http.routers.{wordpress}-web.entrypoints=web"
      - "traefik.http.services.{wordpress}.loadbalancer.server.port=80"
    logging:
      driver: loki
      options:
          loki-url: http://127.0.0.1:3100/loki/api/v1/push
          loki-pipeline-stages: |
            - regex:
                expression: ’(level|lvl|severity)=(?P<level>\w+)’
            - labels:
                level:
volumes:
  db_data:
  wordpress_data:

networks:
  db:
  external:
    external : true