version: "3"

services:
  db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    networks:
      - external
    env_file:
      - ./dbmat.env

  app:
    image: matomo
    restart: always
    volumes:
      - matomo:/var/www/html:z
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file:
      - ./dbmat.env
    ports:
      - 8083:80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.{wordpress}-web.rule=Host(`matomo.td.anthonymoll.fr`)"
      - "traefik.http.routers.{wordpress}-web.entrypoints=web"
      - "traefik.http.services.{wordpress}.loadbalancer.server.port=80"
    networks:
      - external
    logging:
      driver: loki
      options:
          loki-url: http://127.0.0.1:3100/loki/api/v1/push
          loki-pipeline-stages: |
            - regex:
                expression: ’(level|lvl|severity)=(?P<level>\w+)’
            - labels:
                level:

volumes:
  db:
  matomo:

networks:
  external:
    external: true
